### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by tgrennan** [apptimistco/asn#1]
- [x] make test/Main run multiple servers
- [ ] drop connections with repeated ephemeral key
- [ ] transfer blob time to file's mtime and use in searches
- [ ] aggregated asn Tx to N (e.g. 4) instead NSESSION go routines
- [ ] prefix files with SUM instead of writing and linking repos/SUM
- [ ] mark integration of checkin reference and location
- [ ] add: asngrep
- [ ] don't write actual user marks
- [ ] demand cache some files
- [ ] make an administrator configure forum for sub networks
- [ ] optional encrypted blob store
- [ ] add: mirror < NAME | URL >
